### ISSUE TITLE
Package not doing anything

### ISSUE THREAD

**Issue by jdomenechb** [igogo5yo/atom-php-navigation#1]
I have a ZF2 project in Atom, and when I use this plugin, nothing is displayed. When I toogle the plugin, the text "Indexation: please wait!" appears, and after a few seconds, it disappears and nothing else it is shown. Not even an error is thrown.

**Comment by igogo5yo** [comment]
Thanks!
Right now I prepare to release new version of this package and I need some time for reproduce your bug.
Do you use default ZF2 project architecture?

**Comment by igogo5yo** [comment]
I published new release v0.5.0.
In that release I use new better regular expressions and I tested it on ZF2 example application.
Please check this and give me feedback :)

P.S. In new version for navigation use alt+click.

**Comment by calcio** [comment]
Is it only works on MAC? I Try it using Linux end close my window.

**Comment by igogo5yo** [comment]
@Calcio
I tried it only on mac.
Can you give your log? 
I going to fix it for linux and window in next releases or you can contribute to it :)

**Comment by calcio** [comment]
I can't find the log file from ATOM. Where is ti?

**Comment by igogo5yo** [comment]
You can open developer console in atom and get errors - ctrl-alt-l
![console log](http://dl1.joxi.net/drive/0000/2405/10597/150814/47c81f6688.jpg)

**Comment by dymoksc** [comment]
It seems, that it still does nothing on linux, do you plan on implementing linux compatibility? Thank you!

**Comment by igogo5yo** [comment]
Yes, I have plans on implementing linux compatibility in future!
But I do not have much time now :(
