### ISSUE TITLE
Link don't open correct file (.hg)

### ISSUE THREAD

**Issue by bato3** [igogo5yo/atom-php-navigation#7]
For some class it open mercurial repository file, not right file.

.hg/store/[..]/cls.php.i

PHP Framefork: kahana 3.3

Atom v1.8.0 win7 x64

**Comment by igogo5yo** [comment]
Hmm. This is an interesting bug!
I going to try to reproduce it!

**Comment by igogo5yo** [comment]
Fixed! Try it :)
