### ISSUE TITLE
Deprecated selector in `atom-php-navigation/styles/atom-php-navigation.less`

### ISSUE THREAD

**Issue by mdridzuan80** [igogo5yo/atom-php-navigation#8]
In `atom-php-navigation/styles/atom-php-navigation.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .clickable-class .inherited-class,
atom-text-editor::shadow .clickable-class .inherited-class,
atom-text-editor .clickable-class .support.class,
atom-text-editor::shadow .clickable-class .support.class,
atom-text-editor .clickable-class .namespace,
atom-text-editor::shadow .clickable-class .namespace` => `atom-text-editor .clickable-class .inherited-class,
atom-text-editor.editor .clickable-class .syntax--inherited-class,
atom-text-editor .clickable-class .support.class,
atom-text-editor.editor .clickable-class .syntax--support.syntax--class,
atom-text-editor .clickable-class .namespace,
atom-text-editor.editor .clickable-class .syntax--namespace`

* `atom-text-editor .clickable-class .inherited-class:hover,
atom-text-editor::shadow .clickable-class .inherited-class:hover,
atom-text-editor .clickable-class .support.class:hover,
atom-text-editor::shadow .clickable-class .support.class:hover,
atom-text-editor .clickable-class .namespace:hover,
atom-text-editor::shadow .clickable-class .namespace:hover` => `atom-text-editor .clickable-class .inherited-class:hover,
atom-text-editor.editor .clickable-class .syntax--inherited-class:hover,
atom-text-editor .clickable-class .support.class:hover,
atom-text-editor.editor .clickable-class .syntax--support.syntax--class:hover,
atom-text-editor .clickable-class .namespace:hover,
atom-text-editor.editor .clickable-class .syntax--namespace:hover`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by adilsaeed31** [comment]
I have same problem, I install this package just now.

**Comment by brycefranzen** [comment]
Still an issue, but easy to fix.  Just edit the atom-php-navigation/styles/atom-php-navigation.less to the following:
```atom-text-editor .clickable-class .inherited-class,
atom-text-editor.editor .clickable-class .syntax--inherited-class,
atom-text-editor .clickable-class .support.class,
atom-text-editor.editor .clickable-class .syntax--support.syntax--class,
atom-text-editor .clickable-class .namespace,
atom-text-editor.editor .clickable-class .syntax--namespace {
  cursor: pointer;

  &:hover {
    text-decoration: underline;
  }
}
